### PR TITLE
Refactoring of tests

### PR DESCRIPTION
**Pull request by mansimarkaur**
Please review? @marco-c 
Thanks

### CODE REVIEW

**Comment by mansimarkaur** [comment]
Also, is it mandatory to have the following comments on top of every file, be it a test file or a web service file?:
```
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
```

**Comment by marco-c** [comment]
We might remove `test_top_similar_traces.py`, `test_signatures_similarity.py` and `test_signature_coherence.py` at some point, but for now it makes sense to move them in `tests`.

**Comment by mansimarkaur** [comment]
Will we remove them because the part of code they are using should technically be covered by `test_crash_similarity.py`?

**Comment by marco-c** [comment]
> Will we remove them because the part of code they are using should technically be covered by test_crash_similarity.py?

Exactly :)

**Comment by mansimarkaur** [comment]
Why exactly are we choosing to keep them as of now?

**Comment by marco-c** [comment]
> Why exactly are we choosing to keep them as of now?

They were just examples of how to use the `crash_similarity` functions and of the results with some specific signatures. I suppose we can actually remove them now (if we want to see which signatures were tested, we can just look at the git history).

**Pull request merged**
